"""add level_names to tenant

Revision ID: 3895323edb62
Revises: 68b919ba17c2
Create Date: 2026-02-13 19:16:00.538809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3895323edb62'
down_revision: Union[str, Sequence[str], None] = '68b919ba17c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_is_published_tenant_id'), table_name='course')
    op.drop_index(op.f('ix_lesson_order_module'), table_name='lesson')
    op.drop_index(op.f('ix_lessonprogress_user_id_lesson_id'), table_name='lessonprogress')
    op.drop_index(op.f('ix_module_order_course'), table_name='module')
    op.add_column('tenant', sa.Column('level_names', sa.JSON(), nullable=True))
    op.alter_column('user', 'admin_request_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'admin_request_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('tenant', 'level_names')
    op.create_index(op.f('ix_module_order_course'), 'module', ['course_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_lessonprogress_user_id_lesson_id'), 'lessonprogress', ['user_id', 'lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_order_module'), 'lesson', ['module_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_course_is_published_tenant_id'), 'course', ['is_published', 'tenant_id', 'deleted_at'], unique=False)
    # ### end Alembic commands ###
