"""add_one_time_token_model

Revision ID: 4ffc1d5caba6
Revises: e2f1a3b4c5d2
Create Date: 2026-02-21 11:44:37.299689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4ffc1d5caba6'
down_revision: Union[str, Sequence[str], None] = 'e2f1a3b4c5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onetimetoken',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onetimetoken_expires_at'), 'onetimetoken', ['expires_at'], unique=False)
    op.create_index(op.f('ix_onetimetoken_token'), 'onetimetoken', ['token'], unique=True)
    op.create_index(op.f('ix_onetimetoken_user_id'), 'onetimetoken', ['user_id'], unique=False)
    op.drop_constraint(op.f('course_tenant_id_fkey'), 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'tenant', ['tenant_id'], ['id'])
    op.drop_constraint(op.f('lesson_module_id_fkey'), 'lesson', type_='foreignkey')
    op.create_foreign_key(None, 'lesson', 'module', ['module_id'], ['id'])
    op.drop_constraint(op.f('lessonprogress_user_id_fkey'), 'lessonprogress', type_='foreignkey')
    op.drop_constraint(op.f('lessonprogress_lesson_id_fkey'), 'lessonprogress', type_='foreignkey')
    op.create_foreign_key(None, 'lessonprogress', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'lessonprogress', 'lesson', ['lesson_id'], ['id'])
    op.drop_constraint(op.f('messagestore_user_id_fkey'), 'messagestore', type_='foreignkey')
    op.drop_constraint(op.f('messagestore_tenant_id_fkey'), 'messagestore', type_='foreignkey')
    op.create_foreign_key(None, 'messagestore', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'messagestore', 'tenant', ['tenant_id'], ['id'])
    op.drop_constraint(op.f('module_course_id_fkey'), 'module', type_='foreignkey')
    op.create_foreign_key(None, 'module', 'course', ['course_id'], ['id'])
    op.drop_constraint(op.f('tenant_owner_user_id_fkey'), 'tenant', type_='foreignkey')
    op.create_foreign_key(None, 'tenant', 'user', ['owner_user_id'], ['id'])
    op.alter_column('tenantmember', 'is_onboarded',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('tenantmember_user_id_fkey'), 'tenantmember', type_='foreignkey')
    op.drop_constraint(op.f('tenantmember_tenant_id_fkey'), 'tenantmember', type_='foreignkey')
    op.create_foreign_key(None, 'tenantmember', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tenantmember', 'tenant', ['tenant_id'], ['id'])
    op.alter_column('user', 'is_onboarded',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_onboarded',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'tenantmember', type_='foreignkey')
    op.drop_constraint(None, 'tenantmember', type_='foreignkey')
    op.create_foreign_key(op.f('tenantmember_tenant_id_fkey'), 'tenantmember', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('tenantmember_user_id_fkey'), 'tenantmember', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tenantmember', 'is_onboarded',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'tenant', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_owner_user_id_fkey'), 'tenant', 'user', ['owner_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'module', type_='foreignkey')
    op.create_foreign_key(op.f('module_course_id_fkey'), 'module', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'messagestore', type_='foreignkey')
    op.drop_constraint(None, 'messagestore', type_='foreignkey')
    op.create_foreign_key(op.f('messagestore_tenant_id_fkey'), 'messagestore', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('messagestore_user_id_fkey'), 'messagestore', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lessonprogress', type_='foreignkey')
    op.drop_constraint(None, 'lessonprogress', type_='foreignkey')
    op.create_foreign_key(op.f('lessonprogress_lesson_id_fkey'), 'lessonprogress', 'lesson', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('lessonprogress_user_id_fkey'), 'lessonprogress', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lesson', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_module_id_fkey'), 'lesson', 'module', ['module_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key(op.f('course_tenant_id_fkey'), 'course', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_onetimetoken_user_id'), table_name='onetimetoken')
    op.drop_index(op.f('ix_onetimetoken_token'), table_name='onetimetoken')
    op.drop_index(op.f('ix_onetimetoken_expires_at'), table_name='onetimetoken')
    op.drop_table('onetimetoken')
    # ### end Alembic commands ###
