"""add vip_group_link to tenant

Revision ID: 622c0b25fa43
Revises: a1b2c3d4e5f6
Create Date: 2026-02-15 23:40:05.893915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '622c0b25fa43'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('vip_group_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_tenant_owner_user_id'), 'tenant', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_tenantmember_role'), 'tenantmember', ['role'], unique=False)
    op.create_index(op.f('ix_tenantmember_status'), 'tenantmember', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenantmember_status'), table_name='tenantmember')
    op.drop_index(op.f('ix_tenantmember_role'), table_name='tenantmember')
    op.drop_index(op.f('ix_tenant_owner_user_id'), table_name='tenant')
    op.drop_column('tenant', 'vip_group_link')
    # ### end Alembic commands ###
