"""add_performance_indexes_scaling

Revision ID: 6a2713179341
Revises: 622c0b25fa43
Create Date: 2026-02-16 10:06:22.881496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a2713179341'
down_revision: Union[str, Sequence[str], None] = '622c0b25fa43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_lessonprogress_user_recent', 'lessonprogress', ['user_id', sa.literal_column('completed_at DESC')], unique=False)
    op.create_index('ix_tenantmember_joins', 'tenantmember', ['tenant_id', 'joined_at'], unique=False)
    op.create_index('ix_tenantmember_leaderboard', 'tenantmember', ['tenant_id', sa.literal_column('xp DESC'), sa.literal_column('level DESC')], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index('ix_tenantmember_leaderboard', table_name='tenantmember')
    op.drop_index('ix_tenantmember_joins', table_name='tenantmember')
    op.drop_index('ix_lessonprogress_user_recent', table_name='lessonprogress')
    # ### end Alembic commands ###
