"""add content to lesson

Revision ID: 9761eec0256d
Revises: 3895323edb62
Create Date: 2026-02-13 21:20:38.127456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9761eec0256d'
down_revision: Union[str, Sequence[str], None] = '3895323edb62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'content')
    # ### end Alembic commands ###
