"""add mux fields to lesson

Revision ID: 9b959ba4060b
Revises: 9761eec0256d
Create Date: 2026-02-14 10:54:39.916624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b959ba4060b'
down_revision: Union[str, Sequence[str], None] = '9761eec0256d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('mux_asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lesson', sa.Column('mux_playback_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lesson', sa.Column('mux_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'mux_status')
    op.drop_column('lesson', 'mux_playback_id')
    op.drop_column('lesson', 'mux_asset_id')
    # ### end Alembic commands ###
