"""add_performance_and_resilience

Revision ID: add9888af519
Revises: efecdbcbf53d
Create Date: 2026-02-13 00:36:07.611150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'add9888af519'
down_revision: Union[str, Sequence[str], None] = 'efecdbcbf53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('course', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('course', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_course_deleted_at'), 'course', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_course_is_published'), 'course', ['is_published'], unique=False)
    op.create_index(op.f('ix_course_is_vip'), 'course', ['is_vip'], unique=False)
    op.create_index(op.f('ix_course_tenant_id'), 'course', ['tenant_id'], unique=False)
    op.add_column('lesson', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('lesson', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('lesson', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_lesson_deleted_at'), 'lesson', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_lesson_is_published'), 'lesson', ['is_published'], unique=False)
    op.create_index(op.f('ix_lesson_is_vip'), 'lesson', ['is_vip'], unique=False)
    op.create_index(op.f('ix_lesson_module_id'), 'lesson', ['module_id'], unique=False)
    op.create_index(op.f('ix_lesson_order_index'), 'lesson', ['order_index'], unique=False)
    op.create_index(op.f('ix_lessonprogress_completed_at'), 'lessonprogress', ['completed_at'], unique=False)
    op.create_index(op.f('ix_lessonprogress_lesson_id'), 'lessonprogress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lessonprogress_user_id'), 'lessonprogress', ['user_id'], unique=False)
    op.add_column('module', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('module', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('module', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_module_course_id'), 'module', ['course_id'], unique=False)
    op.create_index(op.f('ix_module_deleted_at'), 'module', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_module_is_vip'), 'module', ['is_vip'], unique=False)
    op.create_index(op.f('ix_module_order_index'), 'module', ['order_index'], unique=False)
    op.add_column('tenant', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tenant', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('tenant', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tenant_deleted_at'), 'tenant', ['deleted_at'], unique=False)
    op.add_column('tenantmember', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tenantmember', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('tenantmember', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tenantmember_deleted_at'), 'tenantmember', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tenantmember_joined_at'), 'tenantmember', ['joined_at'], unique=False)
    op.create_index(op.f('ix_tenantmember_tenant_id'), 'tenantmember', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenantmember_user_id'), 'tenantmember', ['user_id'], unique=False)
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_deleted_at'), 'user', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_deleted_at'), table_name='user')
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_index(op.f('ix_tenantmember_user_id'), table_name='tenantmember')
    op.drop_index(op.f('ix_tenantmember_tenant_id'), table_name='tenantmember')
    op.drop_index(op.f('ix_tenantmember_joined_at'), table_name='tenantmember')
    op.drop_index(op.f('ix_tenantmember_deleted_at'), table_name='tenantmember')
    op.drop_column('tenantmember', 'deleted_at')
    op.drop_column('tenantmember', 'updated_at')
    op.drop_column('tenantmember', 'created_at')
    op.drop_index(op.f('ix_tenant_deleted_at'), table_name='tenant')
    op.drop_column('tenant', 'deleted_at')
    op.drop_column('tenant', 'updated_at')
    op.drop_column('tenant', 'created_at')
    op.drop_index(op.f('ix_module_order_index'), table_name='module')
    op.drop_index(op.f('ix_module_is_vip'), table_name='module')
    op.drop_index(op.f('ix_module_deleted_at'), table_name='module')
    op.drop_index(op.f('ix_module_course_id'), table_name='module')
    op.drop_column('module', 'deleted_at')
    op.drop_column('module', 'updated_at')
    op.drop_column('module', 'created_at')
    op.drop_index(op.f('ix_lessonprogress_user_id'), table_name='lessonprogress')
    op.drop_index(op.f('ix_lessonprogress_lesson_id'), table_name='lessonprogress')
    op.drop_index(op.f('ix_lessonprogress_completed_at'), table_name='lessonprogress')
    op.drop_index(op.f('ix_lesson_order_index'), table_name='lesson')
    op.drop_index(op.f('ix_lesson_module_id'), table_name='lesson')
    op.drop_index(op.f('ix_lesson_is_vip'), table_name='lesson')
    op.drop_index(op.f('ix_lesson_is_published'), table_name='lesson')
    op.drop_index(op.f('ix_lesson_deleted_at'), table_name='lesson')
    op.drop_column('lesson', 'deleted_at')
    op.drop_column('lesson', 'updated_at')
    op.drop_column('lesson', 'created_at')
    op.drop_index(op.f('ix_course_tenant_id'), table_name='course')
    op.drop_index(op.f('ix_course_is_vip'), table_name='course')
    op.drop_index(op.f('ix_course_is_published'), table_name='course')
    op.drop_index(op.f('ix_course_deleted_at'), table_name='course')
    op.drop_column('course', 'deleted_at')
    op.drop_column('course', 'updated_at')
    op.drop_column('course', 'created_at')
    # ### end Alembic commands ###
