"""use_jsonb_and_cleanup

Revision ID: cfccdd3e7d81
Revises: add9888af519
Create Date: 2026-02-13 00:38:14.638829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cfccdd3e7d81'
down_revision: Union[str, Sequence[str], None] = 'add9888af519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    op.alter_column('user', 'admin_request_details',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(),
               postgresql_using="admin_request_details::jsonb",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'admin_request_details',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
