"""add gamification tracking and message store

Revision ID: d31ff3246baf
Revises: 6a2713179341
Create Date: 2026-02-16 10:31:29.906171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd31ff3246baf'
down_revision: Union[str, Sequence[str], None] = '6a2713179341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messagestore',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'message_id', name='uq_chat_message')
    )
    op.create_index(op.f('ix_messagestore_created_at'), 'messagestore', ['created_at'], unique=False)
    op.create_index('ix_messagestore_lookup', 'messagestore', ['chat_id', 'message_id'], unique=False)
    op.create_index(op.f('ix_messagestore_tenant_id'), 'messagestore', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_messagestore_user_id'), 'messagestore', ['user_id'], unique=False)
    op.add_column('tenantmember', sa.Column('hourly_xp_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('tenantmember', sa.Column('last_xp_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenantmember', 'last_xp_at')
    op.drop_column('tenantmember', 'hourly_xp_count')
    op.drop_index(op.f('ix_messagestore_user_id'), table_name='messagestore')
    op.drop_index(op.f('ix_messagestore_tenant_id'), table_name='messagestore')
    op.drop_index('ix_messagestore_lookup', table_name='messagestore')
    op.drop_index(op.f('ix_messagestore_created_at'), table_name='messagestore')
    op.drop_table('messagestore')
    # ### end Alembic commands ###
